/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SafetyCarTest {
    @Test
    void testSingleton() {

        SafetyCar mySafetyCar = SafetyCar.getInstance();
        SafetyCar mySafetyCar2 = SafetyCar.getInstance();
        ;
        assertEquals(mySafetyCar, mySafetyCar2);
    }
}
