/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SafetyCarTest {
    @Test
    void testSingleton() {

        SafetyCar mySafetyCar = SafetyCar.GetInstance();
        SafetyCar mySafetyCar2 = SafetyCar.GetInstance();;
        assertEquals(mySafetyCar, mySafetyCar2);
    }
}
