/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class VoitureDeFormuleUnFactoryTest {
    @Test
    void test3Voitures() {
        CircuitDeCourse circuit = new CircuitDeCourse();
        circuit.AddVoitureACourse(VoitureDeFormuleUnFactory.getVoitureDeFormuleUn(Constructeur.MERCEDES));
        circuit.AddVoitureACourse(VoitureDeFormuleUnFactory.getVoitureDeFormuleUn(Constructeur.FERRARI));
        circuit.AddVoitureACourse(VoitureDeFormuleUnFactory.getVoitureDeFormuleUn(Constructeur.RENAULT));
        assertEquals(3, circuit.GetNbVoitures());
    }

    @Test
    void testCouleurVoiture() {
        IVoitureDeFormuleUn mercedes = VoitureDeFormuleUnFactory.getVoitureDeFormuleUn(Constructeur.MERCEDES);
        IVoitureDeFormuleUn ferrari = VoitureDeFormuleUnFactory.getVoitureDeFormuleUn(Constructeur.FERRARI);
        IVoitureDeFormuleUn renault = VoitureDeFormuleUnFactory.getVoitureDeFormuleUn(Constructeur.RENAULT);
        assertEquals("Noire", mercedes.getCouleur());
        assertEquals("Rouge", ferrari.getCouleur());
        assertEquals("Bleue", renault.getCouleur());
    }
}
